### ISSUE TITLE
Hello, can you add a contact information? Teach me how to do it

### ISSUE THREAD

**Issue by panxiong1117** [shiomiyan/noto-sans-1m#1]
Hello, can you add a contact information? Teach me how to do it

**Comment by shiomiyan** [comment]
Hello.
May I ask for more details here?

**Comment by panxiong1117** [comment]
I want to know How can I use this font on windows

**Comment by shiomiyan** [comment]
Do you mean how to generate this font?

Methods are
1. clone this repo
2. Place the original ttf in the repository root ([NotoSansMono-Regular.ttf](https://github.com/notofonts/noto-fonts/blob/main/hinted/ttf/NotoSansMono/NotoSansMono-Regular.ttf) and migu-1m-regular.ttf (included [here](https://osdn.net/projects/mix-mplus-ipa/downloads/72511/migu-1m-20200307.zip/)))
3. follow the README (sorry for Japanese document)

I will be more likely to support you if you clarify which step you are having trouble with.
